### ISSUE TITLE
Code Issuses

### ISSUE THREAD

**Issue by zhuofsky** [cpark88/SyNCRec#7]
Hello, it is a great honor to read this best paper and I learnt some interesting perspective. But I have some issues about the code. I would appreciate it if you solve my confusion!
## 1. How to process the Amazon dataset in your paper?
By analyzing your small-sized temporary raw data, I guess which version of Amazon dataset you used is version 2018. But in the processing step，I filter the raw data by setting 5-core for users  and items, 0 for the threshold of rating and ensure in every user there are five domains data. But after the processing step, I could't get the same amount of data as you did. So could you give more details about how to process the raw data?
![image](https://github.com/user-attachments/assets/01400fd9-e651-4ccd-8189-6af405223224)
## 2. Why does the model performance decrease after the first epoch?
Because I only have one A100 GPU for training the model, I deleted the code about distributed training. In addition to this, I didn't do any changes. But in the training stage, I  found that the HIT, NDCG, MRR were decreasing as the number of epochs increasing. I think the code is very clear, but I don't know why is that. I would be thankful if you could give me some advice to check it! 
![image](https://github.com/user-attachments/assets/cd698856-37e9-4177-8add-fda96b5b7679)
![image](https://github.com/user-attachments/assets/b96c4965-974e-40f8-8a48-be6020a87ee3)

**Comment by Edwardyan1112** [comment]
> Hello, it is a great honor to read this best paper and I learnt some interesting perspective. But I have some issues about the code. I would appreciate it if you solve my confusion!
> 
> ## 1. How to process the Amazon dataset in your paper?
> By analyzing your small-sized temporary raw data, I guess which version of Amazon dataset you used is version 2018. But in the processing step，I filter the raw data by setting 5-core for users and items, 0 for the threshold of rating and ensure in every user there are five domains data. But after the processing step, I could't get the same amount of data as you did. So could you give more details about how to process the raw data? ![image](https://private-user-images.githubusercontent.com/78064143/367648928-01400fd9-e651-4ccd-8189-6af405223224.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MjEyNDIsIm5iZiI6MTczNDUyMDk0MiwicGF0aCI6Ii83ODA2NDE0My8zNjc2NDg5MjgtMDE0MDBmZDktZTY1MS00Y2NkLTgxODktNmFmNDA1MjIzMjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDExMjIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NGU4NDE3ZDllYzUzMzNlMWI1MTVlZTdkYWIxNjM4ZTM4YTA4M2VhNTBlN2QyNTUyNmRmYTg3NWE4MDBkYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jDJOwZRlUDbQPseMCJx-53DZvy8jyogTbXtxK42ZEwk)

Hello, I am focusing on preprocessing the Amazon dataset. Have you found a method to ensure the amount of data consistency as reported in the paper?

**Comment by cpark88** [comment]
> > Hello, it is a great honor to read this best paper and I learnt some interesting perspective. But I have some issues about the code. I would appreciate it if you solve my confusion!
> > ## 1. How to process the Amazon dataset in your paper?
> > By analyzing your small-sized temporary raw data, I guess which version of Amazon dataset you used is version 2018. But in the processing step，I filter the raw data by setting 5-core for users and items, 0 for the threshold of rating and ensure in every user there are five domains data. But after the processing step, I could't get the same amount of data as you did. So could you give more details about how to process the raw data? ![image](https://private-user-images.githubusercontent.com/78064143/367648928-01400fd9-e651-4ccd-8189-6af405223224.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MjEyNDIsIm5iZiI6MTczNDUyMDk0MiwicGF0aCI6Ii83ODA2NDE0My8zNjc2NDg5MjgtMDE0MDBmZDktZTY1MS00Y2NkLTgxODktNmFmNDA1MjIzMjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDExMjIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NGU4NDE3ZDllYzUzMzNlMWI1MTVlZTdkYWIxNjM4ZTM4YTA4M2VhNTBlN2QyNTUyNmRmYTg3NWE4MDBkYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jDJOwZRlUDbQPseMCJx-53DZvy8jyogTbXtxK42ZEwk)
> 
> Hello, I am focusing on preprocessing the Amazon dataset. Have you found a method to ensure the amount of data consistency as reported in the paper?

For a dataset like Amazon, which has over 500,000 items, it seems that at least 100,000 users’ history is necessary. If the user count is below 30,000, it tends to lead to overfitting:)
